### ISSUE TITLE
If I draw, then record, recording does not show previous drawing

### ISSUE THREAD

**Issue by swakulchik** [ThrivingKings/whiteboard-gadget#18]
Right now, If i create a drawing, then create a recording, none of the previously drawn lines will appear during (or after) the recording 

http://screencast.com/t/Rupf7HoV

**Comment by ThrivingKings** [comment]
I've played with this a bit and I'm starting to think it may not actually be a bug. The reason being: what about the drawings I complete in-between or after recordings? Let's say, I draw a little, then record a little, then draw a little more, then record again. If I didn't record the actions, why should I expect them to appear in order, along with the recorded actions? I sort of feel like if I want things to appear in a certain order, I (as the author) should just record them in that order.

What do you guys think?

**Comment by devonashleyberger** [comment]
This is what I think.. 

There are 3 layers: 
1. Background image
2. Drawing on top of the background image
3. Recording

For the sake of a MVP, we should limit the recording to a one shot deal. If this is the case, the 2nd item (drawing on top of the background) becomes part of the background (in the eyes of the learner) and the recording plays over it.
