### ISSUE TITLE
button styles

### ISSUE THREAD

**Issue by devonashleyberger** [ThrivingKings/whiteboard-gadget#20]
![screen shot 2014-09-03 at 11 29 26 am](https://cloud.githubusercontent.com/assets/3409198/4139208/457c40ba-3398-11e4-931e-f9bd2522c7d2.png)

Buttons should have a height of 24px and have 10px of margin between the two in this case: 
![screen shot 2014-09-03 at 11 17 11 am](https://cloud.githubusercontent.com/assets/3409198/4139033/8aaf5aca-3396-11e4-8e03-7c037cd60c45.png)

Font should be Avenir-next, #ffffff and lowercase

Button colors: 
[clear canvas]
# 7c7975 (default)
# 6f6c69 (hover)
# 625f5c (active)

[record]
# ce3e30 (default)
# be392c (hover)
# ae3429 (active)

[play]
# 3a968a (default)
# 35887d (hover)
# 2f7a70 (active)

disabled buttons and icons:
# f2f1ed

font-color: #c7c3be

**Comment by ThrivingKings** [comment]
hi @devonashleyberger, do you have a color set for the record button once it becomes "active" and is actually recording? Right now, I'm just changing the font color.

**Comment by devonashleyberger** [comment]
I think color may not be the most clear indicator. I have 2 ideas: 
1. Have the dot within the button blink when recording is active. This would be my first choice because it's a convention most users will understand and be comfortable with.  
2. If the first option is too difficult, a good back-up plan would be to italicize the word "record" within the button. This is the way we deal with "pending" states of buttons in versal.com so it wouldn't be to much of a stretch. 

Yeah?

**Comment by ThrivingKings** [comment]
sounds good, thanks for the quick response
